### ISSUE TITLE
wishlist: persistence

### ISSUE THREAD

**Issue by aaannndddyyy** [alnf/toxcore#1]
Chats should be persistent over restarts (just like a friend stays in my friend list, the chat should stay and when I restart my client, the chats should all be there, unless I left them.)
Joining them automatically.

**Comment by alnf** [comment]
Joining chats automatically is not a problem. Still you will need to find peers every time, cause they IP might change, though pks of peers are stored.

**Comment by aaannndddyyy** [comment]
good. :)
Some peer info should be stored in case it's a hidden group. Even if that cannot guarantee you'll find the peer still at the same ip. If you don't find any, you'll need to be re-invited.
Also invite cert needs to be stored over restarts.

**Comment by alnf** [comment]
You should rather consider group chat as a way to find each other, so "any user who was part of that group can resume it" comes naturally. It would be possible to request chat log (or either sync) from any online member. As for offline messaging - it's totally another issue.

**Comment by alnf** [comment]
I close it, cause we discuss it in #51 now.
