### ISSUE TITLE
wishlist: operatorless, unmoderated chats

### ISSUE THREAD

**Issue by aaannndddyyy** [alnf/toxcore#11]
One of the great new things in your group chats are roles and kicks and bans. 
However, some people prefer to have a place where nobody but the user himself decides whetehr or not someone should be ignored. 
Such an anarchic chat should be GUARANTEED to be PERMANENTLY operatorless/unmoderated.
So even the founder cannot come and claim back his channel later.
Ideally there is NO founder.
So in totally opless groupchats every user has the option to mute other group member's audio for them locally and/or to ignore their text messages. 
Currently a founder is needed for roles and for chatid. In anarchic chats there would be no roles so that's not an issue. To be really sure noone would possibly be able to claim ownwership, there should be no founder at all, and in this case, the chatid should be the hash of the (founderless and opless) unchangeable chat manifest.
All decisive characteristics of the chat are stored in the manifest; only unchanging propperties. 
If it is anarchic, no founder would be present at all. So that in a popular anarchic channel the founder cannot later change his mind and take over the anarchic channel anymore.

That would make group chats extremely flexible, ranging from

a moderated chat with a founder and operators (of maybe different ranks) - a hierarchical moderated chat,
to temporarily unmoderated chats (no op's only founder, who might be even offline, hence either moderated by founder or temporarily anarchic) and to
permanently anarchic chats, where there is not even a recoginizable founder (each user can only ignore locally)

**Comment by aaannndddyyy** [comment]
This would also solve the problem mentioned on https://github.com/alnf/toxcore/wiki/GC-Types :  "In the opposite case when new manifest is less strict it might create troubles, cause new peers won't listen to the rules. So we advice to create a new chat (or maybe someone will compe up with a better solution)."

Here, you simply cannot change the chat manifest without automatically creating a new chat.
if you have a moderated chat, you could have a chat manifest that has three values and not just two, for some entries. one for permantently true (1), one for permanently false (-1) and one for not set, aka subject to change (0)

**Comment by alnf** [comment]
@JFreegman closing?

**Comment by JFreegman** [comment]
This can easily be achieved by the founder leaving the group and joining it again. We don't need to add it as yet another feature.
