### ISSUE TITLE
wishlist: invite-only groups

### ISSUE THREAD

**Issue by aaannndddyyy** [alnf/toxcore#13]
group chats that can be found in the dht with their chatid, but cannot be joined unless a valid invitation certificate is presented by the user who wants to join.
It still needs to be in the DHT, so that the user can always find the chat even after long disconnects.

**Comment by alnf** [comment]
Yeah, that is a nice feature.

**Comment by aaannndddyyy** [comment]
This allows password-protected groups too. Via zero knowledge proof a new peer and a random member of the group check whether their passwords match and whether no failed attempts were made by that peer before. If PW matches, the group member invites him.

**Comment by alnf** [comment]
@JFreegman if we have proper password protection now we can close this.

**Comment by JFreegman** [comment]
@alnf right.
