### ISSUE TITLE
wishlist: hidden groups

### ISSUE THREAD

**Issue by aaannndddyyy** [alnf/toxcore#14]
group chats that are not in the DHT at all and cannot be joined unless a valid invitation certificate is presented by the user who wants to join.
You'd need a direct invitation from a friend that is conencted to you, or an invitation ceritficate and know a group member to connect to.
So these would very much resemble current group chats. If you have an unmoderated hidden group, you basically have old groupchats - except for rejoining and preventing duplicate nicks.
For friends, this might be the default group chat mode: all are equal.

For keeping a high level of user comfort, autorejoin should be tried for those group chats too, by trying to connect to the last known nodes you have seen online.

**Comment by alnf** [comment]
@JFreegman closing?

**Comment by JFreegman** [comment]
This is implemented, closing.
