### ISSUE TITLE
Chat history sync

### ISSUE THREAD

**Issue by alnf** [alnf/toxcore#22]
Considering signing every message, so peers cannot fake it, when distributing chat history for peers, who've just came online.

**Comment by aaannndddyyy** [comment]
@alnf: If you throw overboard signing each message, you need not abandon chat sync altogether. You should consider chat history sync as an untrusted service by other peers. They **say** that what they send you is what was actually said by others. If you do not trust only one peer, sync with two and compare. That should give you a reasonable level of confidence.

**Comment by aaannndddyyy** [comment]
If group chats are consistent, you can easily hash the received history sync from time A to time B and request from the second peer only the hash of the same time period, in order to compare them. 
At least, if timestamps are the ones of when the message was sent, and not when it was received.
