### ISSUE TITLE
Reduce packets lenght

### ISSUE THREAD

**Issue by alnf** [alnf/toxcore#25]
Enc might be not necessary if we can somehow replace it with peernum.
Nonce is not necessary (c) irun.
Two keys in the header is too much.

**Comment by alnf** [comment]
@JFreegman I would discuss it in the very near future.

**Comment by JFreegman** [comment]
We could use a jenkins hash of the peer's PK for a (probably) unique peernumber. Same thing we do to identify group packets. That would reduce 128 bytes to 8 bytes.

**Comment by alnf** [comment]
Can we close the issue, @JFreegman?

**Comment by JFreegman** [comment]
we can
