### ISSUE TITLE
wishlist: autorejoin

### ISSUE THREAD

**Issue by aaannndddyyy** [alnf/toxcore#3]
autorejoin if connection is lost, would be very much appreciated for an irc-like experience if you don't want to miss what's going on in the chat.
An exception should be: When you got kicked you should not automatically reconnect, but the user must reconnect manually. (Should be one click only, though.)

**Comment by alnf** [comment]
Nice feature.We'll have it in mind.

**Comment by JFreegman** [comment]
that's already implemented, I don't know if it works though

**Comment by aaannndddyyy** [comment]
Even though a kick is not a ban, if you autorejoined after a kick, the kick would have very little impact. The user should be aware of the fact that he was kicked and thus have an opportunity to think about possible reasons. 
That said, a kick might come accompanied with a kick note where the op can leave a message.

**Comment by aaannndddyyy** [comment]
as with all of my wishlist issues here, I have no clue about current state of implementation, and maybe it's all there already. In that case, and after testing, just close the corresponding ticket, or let me know that I only stated the obvious and I'll close it.

**Comment by aaannndddyyy** [comment]
related: #1

**Comment by alnf** [comment]
We'll close it ourselves after testing functionality.

**Comment by alnf** [comment]
Autorejoin works now.
