### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by aaannndddyyy** [alnf/toxcore#31]
On https://github.com/alnf/toxcore/wiki/GC-Announce some text is missing. Just search for "????" to find the place

**Comment by alnf** [comment]
Edited the page

**Comment by aaannndddyyy** [comment]
you re-introduced wrong English. But at least the incomplete sentence is now gone. Your main problems seem to be the use of the comma and of articles. As you don't want others to fix those mistakes, I advise you to refresh your knowledge wrt to the problems I pointed out.
