### ISSUE TITLE
Useless one line functions?

### ISSUE THREAD

**Issue by dubslow** [alnf/toxcore#32]
Something like [`send_group_invite_packet`](https://github.com/JFreegman/toxcore/blob/new_groupchats/toxcore/Messenger.c#L1048), though I'm sure there are others. Apparently that's an artifact from current GCs, so... @irungentoo, why bother with such a function whose only purpose is to waste a stack frame?

**Comment by aaannndddyyy** [comment]
@dubslow you still need invites in new groupchats.
Difference is that they can be issued automatically and by peers that you are not friends with.

**Comment by dubslow** [comment]
All I meant is a coding style thing. Wherever send_group_invite_packet is called, it should instead be replaced by a direct call to write_cryptpacket.

**Comment by aaannndddyyy** [comment]
oh. Sorry I misread you.

**Comment by JFreegman** [comment]
The idea is that write_cryptpacket is a lowish level function which should be hidden from higher level function calls. Abstraction is your friend.

**Comment by alnf** [comment]
I think we should close this. Also it should not be neccessarily "write_cryptpacket" inside, cause core might change and so on. I vote for abstraction.
