### ISSUE TITLE
wishlist: operators op'ing others

### ISSUE THREAD

**Issue by aaannndddyyy** [alnf/toxcore#4]
Not only founder should be able to op other users, but also op's. (Founder could even go missing in action)
Of course, if there are several ranks or positions in a hierarchy, an op of a given rank can only op others up to the same rank as he himself is, not higher. Lower and equal should both be possible.

Revocation of ops:
- 1) Founder can deop everyone (revoke his op cert)
- 2) Nominating op Norma (the one who op'ed Olaf) can revoke Olaf's op status (even if they both are same rank)
  in anarchic chats there are no ops and hence no revocations whatsoever
- 3) Someone of higher rank can revoke certs of lower rank, but generally (with the above exception, op's of same rank cannot deop each other).
- 4) If he was opped by more than one op, then revokation can only be done by all of those together (a revocation cert only revokes one cert, not a bunch of certs), or by someone higher in hierarchy (ultimatively always by the founder).

So an op can op another chat member. If there are more levels, op can give lower levels and up to his own level, but not higher. op can only be deoped by a) someone higher in hierarchy, or  b) the one(s) who op'ed him.

A revoked op's rulings would be ignored.

**Comment by alnf** [comment]
For start, founder will be able to op users, and ops will be able to op users. Only founder will be able to deop. It's for simplicity, it's better to add more complex design later. In anarchy chats all this is neglected.

**Comment by aaannndddyyy** [comment]
yes, step by step. No need to have it all like this in the beginning. 
Neglecting is one thing, straight away not having it is even better. If there **is no** founder or op, then there's also no question whether to neglect him or not. No founder key, means no one can claim to be founder.

**Comment by aaannndddyyy** [comment]
The de-op'ing of op's by other op's is necessary because founder could be gone. And we want to be able to maintain order in the group, nonetheless.

**Comment by alnf** [comment]
@JFreegman we should probably close this, no?

**Comment by JFreegman** [comment]
This is not technically feasible unfortunately. The certificate chain idea had a number of major issues.

**Comment by alnf** [comment]
Note: it's not like the idea is wrong, it's just unreasonably difficult.
