### ISSUE TITLE
"can thus be readily verified against his clientid." shouldn't that be "chatid"

### ISSUE THREAD

**Issue by aaannndddyyy** [alnf/toxcore#42]
https://github.com/alnf/toxcore/wiki/General-GC-rules

**Comment by aaannndddyyy** [comment]
or do you refer to the sanctioned user? make it unambiguous!

**Comment by alnf** [comment]
It should be peerid

**Comment by aaannndddyyy** [comment]
good. so as I thought. op signs, people check op's sig on ban cert and check chatid's sig on op's op cert. Now it is better.
But why are my tickets about ambiguities and all my other wiki-related tickets tagged as invalid? They aim to improve the understandability and quality of your documentation!! @Jfreegman is on a crusade against me, lol.

**Comment by JFreegman** [comment]
We just don't want the issue tracker to be filled up with dozens of spammy 1-word issues that all belong in a single issue while bumping down other more important issues.
