### ISSUE TITLE
wishlist: private/personal messages

### ISSUE THREAD

**Issue by aaannndddyyy** [alnf/toxcore#5]
Sending private personal messages to other group members without being on their friendlist.

**Comment by alnf** [comment]
I think it should be already implemented. At least for current design sending messages to all or to only one peer doesn't matter. Nobody is in your friendlist. Will close this issue after testing.

**Comment by aaannndddyyy** [comment]
great. :)

**Comment by alnf** [comment]
PMs are implemented. You may want to try out with toxic /whisper command.
