### ISSUE TITLE
persistent chat

### ISSUE THREAD

**Issue by aaannndddyyy** [alnf/toxcore#51]
is implemented but is not working properly.

**Comment by dubslow** [comment]
Details please

**Comment by JFreegman** [comment]
I'm currently refactoring it a bit, it should be working properly soon.

**Comment by aaannndddyyy** [comment]
@dubslow: maybe it is already moot because of the refactoring. But with current code, I can create a group, then close toxic. Then I open toxic again, and the group is still there. As expected.
However, if I created the group, wait some time. Maybe an hour or more, then close toxic and immediatelly reopen it, the group is gone. Expected result: group still open / I in group. Actual result: no group tab open.
Only tested with an empty group so far as group id is not working here.

**Comment by dubslow** [comment]
Maybe a one-person group is counted as invalid or something? At any rate yes, best wait for the refactoring

**Comment by JFreegman** [comment]
I'm not sure why that would happen (something to do with the load failing), but I just pushed the refactor so please let me know if that problem persists. Also, connecting to saved groups will be slow/unreliable for now because it uses the DHT instead of trying to connect directly to peers. That's on the TODO list.

**Comment by aaannndddyyy** [comment]
Testing now.
I think, for saved chats the manifest should be stored too.  Not sure about lists of ops when they come. You'd want to sync anyway as soon as you connect, because those could have changed. But then again, tthose changes are likely not so often, so storing them and just hashing over the entire list could make sense.

**Comment by aaannndddyyy** [comment]
chatid is not saved!

**Comment by aaannndddyyy** [comment]
update: in previous run the group was still there, /chatid gave back only 00000000000000000...

tried again, opening two groups.
After reopen, only one was still there. This time, name and chatid were remembered. But the first of the two groups vanished.

**Comment by alnf** [comment]
I think we did it. @JFreegman close it if you think so:D

**Comment by JFreegman** [comment]
Yes, chats are fully persistent now and will even survive if everyone leaves.
