### ISSUE TITLE
wishlist: friend request through gc

### ISSUE THREAD

**Issue by aaannndddyyy** [alnf/toxcore#6]
add a group chat member to your contact list by sending him a friend request.
This could leverage the pm feature.

**Comment by aaannndddyyy** [comment]
I mean, you can manually do it, with pm's, but for good ux, that soudl be automated. Rightclick on a peer and choose "add as friend".
This is mostly (maybe even entirely?) a client thing. But I think, core should handle those messages differently so that it is not a normal text message being displayed to the user. 
( cf. [tagging file transfers with MIME-type information](https://github.com/irungentoo/toxcore/pull/1148) )

**Comment by landswellsong** [comment]
The way groupchats are intended to work now implies that given your group chat id, the peer can not get your "real" one. There will be a functionality to pierce this layer on mutual agreement.

**Comment by aaannndddyyy** [comment]
Yes, but a custom pm could be used for that.

**Comment by landswellsong** [comment]
We want it to be more flexible as in, the identities are only discovered in a risk-free fashion when both sides agree.

**Comment by aaannndddyyy** [comment]
sounds complicated. 
The simple approach would only reveal the identity of the one requester first. and the receiver's identity would only be revealed by accepting the friend request.
So you suggest that I can offer friending someone but even while I offer this, I do not reveal my own pk yet, but only after the other side has agreed to reveal his too? This sounds almost impossible to me, as he could always present a fake id.
Also note, that I wrote that pm's **could** play their part in a solution, not that they have to. So this issue is about a feature of adding a freidn from groupchat. Either it works or it is decided that this feature will not be supported, but not the how. If you find a more flexible way to do it that does not send any private message to the other peer, then fine, though I'm curious what this would be.

**Comment by aaannndddyyy** [comment]
the simple approach I advocate for is:

Alice and Anna are nicks in an anon chat.

Alice wants to add Anna to her friends list. She sends Anna an authenticated (by Alice (her chat id))) pm telling her that she'd like to befriend her and a nonce.

Anna
- receives that request, 
- verifies it came from Alice (the chat id) - as all pm's are checked, this is no additional step
- decides whether to add her or not.

If she does not want to add her, she replies with a negative.
If she agrees to expose keys and adds her, she replies with her real toxid without nospam, another random nonce, and the nonce that she has received from Alice, signed with Anna's real tox id in an authenticated (by Anna (her chat id))) pm.

Alice
- receives that message, 
- verifies it came from Anna (the chat id) - as all pm' are checked, this is no additional step
- checks the signature on the nonce
- checks the nonce
- now knows that the pk really belongs to Anna
- adds Anna to her friend list*
- signs Anna's nonce with her long time real id.
- sends Anna Alice's real tox id without nospam and the signed nonce

Anna
- receives that message, 
- verifies it came from Alice (the chat id) - as all pm's are checked, this is no additional step
- checks the signature on the nonce
- checks the nonce
- now knows that the pk really belongs to Alice
- adds Alice to her friend list*
- unless she's already in there. Then she marks Alice/Anna in the chat as known and writes her friendlist name in the chat in paranthesis.
  (You don't want to totally substitute it, as the Anna/Alice will want to refer to Alice/Anna in the group as Alice/Anna (the chat name) and not her real name.)

This is a 3-message setup

1) Alice:   _add_request_            ------>   Anna
2) Anna:  _add_answer_long_    ------>   Alice
3) Alice:   _add_answer_short_  ------>   Anna

Both parties reveal their own PK to each other if both agree, but that is always the case, as you cannot add friends without adding them. A risk-free way to do that, i.e. guaranteing simulataneous truthful disclosure of pubkeys of both sides, is impossible.
As it is done in a deniable pm (and therefore authenticated as coming from Anna/Alice;  and ownership is also proven) this is as save as it can get. The asked peer reveals his tid first. If you want that the requester also be the first to reveal his key, you can easily tweak it to a 4 message setup:

1) Alice:   _add_request_            ------>   Anna
2) Anna:  _add_cofirm_              ------->  Alice    (this message only contains a boolean and a nonce)
3) Alice:  _add_answer_short_    ------>   Anna  
(if you opt against the nonce in previous message, use here _add_answer_long_)
4) Anna:   _add_answer_short_  ------>   Alice

All this is hard for a user to do, but very basic cryptographic actions. Only two messages and only signing and verification of signatures is involved. That's why this shhould be an automated process.
It's not high priority, because as soon as you have pm's, user can do the id exchange also manually. But  eventually this scheme, or something similar, should be adopted, mainly in order to improve UX, but also in order to make it a bit more secure.

This way Alice' real pk is only revealed when she wants to reveal it, and only to Anna,
and Anna's real pk is also only revealed if she agrees to reveal it, and only to Alice.

**Comment by alnf** [comment]
@landswellsong wrote:
"We want it to be more flexible as in, the identities are only discovered in a risk-free fashion when both sides agree."
Actually, don't know how to do it. As @aaannndddyyy said there is always possibility of giving fake id (which you created just now or smth like that). And if we do not care about that, how to make so both sides reveal their ids simultaneously? Seems impossible. The one who sends message first is in disadvantage.

**Comment by aaannndddyyy** [comment]
"how to make so both sides reveal their ids simultaneously?"  This is not possible.

**Comment by alnf** [comment]
@JFreegman I think we should close it and don't implement anything additional as it is impossible to reveal both sides ids simultaneously. Let it be up to user if he wants to send his tox id in pm.

**Comment by JFreegman** [comment]
@alnf Agreed. This seriously over-complicates something that's as easy as sending a PM.
