### ISSUE TITLE
wishlist: anon chats

### ISSUE THREAD

**Issue by aaannndddyyy** [alnf/toxcore#7]
a chat were your real tox id / public key is not revealed to any chat party (unless you send a FR in PM), and used keys are also not derived from that key.

**Comment by alnf** [comment]
Closing this, cause current design is as you described it. And we don't want to change it if possible. It is better to add functionality in case you want to use your real pk than in opposite case.

**Comment by aaannndddyyy** [comment]
will the user's key used for group chats be per session or persist?
i.e. can i recognize peers who were in the chat yesterday and are again today by something else as only user-defined nick?
talking about the pubkey. the symmetric crypto is per sesssion anyway, but the asymmetric one?

**Comment by JFreegman** [comment]
@aaannndddyyy the plan is to make it persistent

**Comment by aaannndddyyy** [comment]
good. this will help with #3 in hidden groups ( #7 ). in other cases it should be configurable as to prevent user tracking.
